### ISSUE TITLE
clarification of the functionality.

### ISSUE THREAD

**Issue by ihsinme** [mnaydenov/FreeImage-Adv#5]
Good afternoon.
I am confused about the use of tmpnam functions in your code.

https://github.com/mnaydenov/FreeImage-Adv/blob/44e88a61ca021114ae7b868f222f1d0076dfb353/Source/LibJXR/image/encode/strenc.c#L485

If you want to get an unused name on the system.
do you consider the threat, the file can be created between scan and open?

thanks for taking the time to answer.

**Comment by mnaydenov** [comment]
Hello, LibJXR is an external library, originally provided by Microsoft, and part of the original FreeImage repo. I haven't personally reviewed the external libs other than making them compile. The library itself has a github clone ([jxrlib](https://github.com/4creators/jxrlib)), may be You can ask Your question there. 
Thanks for the interest.
